-- vim.pack.add({ "https://github.com/rachartier/tiny-code-action.nvim" })
--
-- require("tiny-code-action").setup({
--   backend = "delta",
--   picker = {
--     "buffer",
--     position = "cursor",
--     auto_preview = "true",
--   },
--   signs = {
--     quickfix = { "", { link = "DiagnosticWarning" } },
--     others = { "", { link = "DiagnosticWarning" } },
--     refactor = { "󰩫", { link = "DiagnosticInfo" } },
--     ["refactor.move"] = { "󰪹", { link = "DiagnosticInfo" } },
--     ["refactor.extract"] = { "", { link = "DiagnosticError" } },
--     ["source.organizeImports"] = { "", { link = "DiagnosticWarning" } },
--     ["source.fixAll"] = { "󰃢", { link = "DiagnosticError" } },
--     ["source"] = { "", { link = "DiagnosticError" } },
--     ["rename"] = { "󰑕", { link = "DiagnosticWarning" } },
--     ["codeAction"] = { "", { link = "DiagnosticWarning" } },
--   },
-- })
--
-- require("which-key").add({
--   mode = { "n" },
--
--   { "gra", "<cmd>CodeAction<cr>", desc  "Code action" },
-- })
