return {
  enabled = true,
  icon = ' ',
  icon_hl = 'SnacksInputIcon',
  icon_pos = 'left',
  prompt_pos = 'title',
  win = {
    backdrop = false,
    border = 'solid',
    title_pos = 'center',
    height = 1,
    width = 40,
    relative = 'cursor',
    row = -3,
    col = 0,
    keys = {
      n_esc = { '<esc>', { 'cancel' }, mode = 'n', expr = true },
      i_esc = { '<esc>', { 'stopinsert' }, mode = 'i', expr = true },
      i_cr = { '<cr>', { 'confirm' }, mode = 'i', expr = true },
      i_ctrl_h = { '<c-h>', '<c-s-w>', mode = 'i', expr = true },
      i_ctrl_k = { '<c-k>', { 'hist_up' }, mode = { 'i', 'n' } },
      i_ctrl_j = { '<c-j>', { 'hist_down' }, mode = { 'i', 'n' } },
      i_ctrl_l = { '<c-l>', { 'confirm' }, mode = { 'i', 'n' } },
      i_ctrl_c = { '<c-c>', 'cancel', mode = 'i', expr = true },
    },
  },
  expand = true,
}
